### ISSUE TITLE
Handle other answers

### ISSUE THREAD

**Issue by jacekelgda** [x-team/unleasher-bot#27]
Right now bot will understand yes, no when asking question but will break on weird answers

<img width="568" alt="screen shot 2017-10-13 at 15 31 50" src="https://user-images.githubusercontent.com/1003372/31548631-bf9df7c2-b02b-11e7-8d89-749f8c80896f.png">

This needs to be fixed. When bot doesn't understand answer, it should say: "Sorry, I did not understand that. Let me repeat the question"

**Comment by cristianossd** [comment]
It sounds interesting. I'll work on this

**Comment by jacekelgda** [comment]
Awesome Cristiano :fives:
